### ISSUE TITLE
Error: "Display must be created on main thread due to Cocoa restrictions."

### ISSUE THREAD

**Issue by sschmitt98** [PSemFlugSim/client#1]
Got this error on Mac OS X 10.10.3 (swt.jar for Mac OS in classpath) clicking "OK" in the second popup window asking for the port to connect to:

```
***WARNING: Display must be created on main thread due to Cocoa restrictions.
Exception in thread "main" org.eclipse.swt.SWTException: Invalid thread access
    at org.eclipse.swt.SWT.error(Unknown Source)
    at org.eclipse.swt.SWT.error(Unknown Source)
    at org.eclipse.swt.SWT.error(Unknown Source)
    at org.eclipse.swt.widgets.Display.error(Unknown Source)
    at org.eclipse.swt.widgets.Display.createDisplay(Unknown Source)
    at org.eclipse.swt.widgets.Display.create(Unknown Source)
    at org.eclipse.swt.graphics.Device.<init>(Unknown Source)
    at org.eclipse.swt.widgets.Display.<init>(Unknown Source)
    at org.eclipse.swt.widgets.Display.<init>(Unknown Source)
    at de.gymolching.fsb.gui.Controller.<init>(Controller.java:63)
    at de.gymolching.fsb.gui.Controller.main(Controller.java:19)
```

**Comment by DominikHorn** [comment]
SWT = "Cross Platform Compatibility with ease" ... It works fine on windows ..

**Comment by DominikHorn** [comment]
According to SWT FAQ:

"Your Application needs to be started with '-XstartOnFirstThread' Argument on OSX"

https://www.eclipse.org/swt/faq.php#swtawtosxmore

**Comment by sschmitt98** [comment]
Unfortunately, the application does not start at all using this argument. Not even the popups are displayed.

**Comment by DominikHorn** [comment]
Fixed with workaround commit
